
import json
from pathlib import Path

def main():
    notebook_path = Path("notebooks/flare_notebook.ipynb")
    print(f"Loading notebook: {notebook_path}")

    with open(notebook_path, 'r') as f:
        nb = json.load(f)

    # 1. Update Imports (Cell 0)
    # Check if visualization import is already there
    cell0_source = nb['cells'][0]['source']
    has_viz_import = any('src.visualization' in line for line in cell0_source)

    if not has_viz_import:
        print("Adding src.visualization imports to Cell 0...")
        # Add to the end of imports
        # Find the last import line or just append
        cell0_source.append('\n')
        cell0_source.append('# Migrated visualization module\n')
        cell0_source.append('from src.visualization import (\n')
        cell0_source.append('    plot_flare_frequency,\n')
        cell0_source.append('    plot_total_energy,\n')
        cell0_source.append('    plot_max_energy,\n')
        cell0_source.append('    plot_cumulative_energy,\n')
        cell0_source.append('    STAR_COLORS\n')
        cell0_source.append(')\n')
        nb['cells'][0]['source'] = cell0_source

    # 2. Append Verification Cells
    # Check if we already added them (look for "Migration Verification")
    has_verification = any('# Migration Verification' in ''.join(c['source']) for c in nb['cells'])

    if has_verification:
        print("Verification cells already exist. Skipping append.")
    else:
        print("Appending verification cells...")

        cells_to_add = []

        # Header
        cells_to_add.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Migration Verification\n",
                "The following cells reproduce the plots using the new `src.visualization` module.  \n",
                "These plots should be identical to the ones generated by the legacy code cells above."
            ]
        })

        # Flare Frequency
        cells_to_add.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Flare Frequency Plot (Reproducing Legacy Cell 3-6)\n",
                "print(\"Plotting Migrated Flare Frequency...\")\n",
                "fig_freq = plot_flare_frequency(\n",
                "    all_stars_detectors, \n",
                "    output_filename=\"migrated_freq_plot.pdf\"\n",
                ")"
            ]
        })

        # Total Energy
        cells_to_add.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Total Flare Energy Plot (Reproducing Legacy Cell 7-8)\n",
                "print(\"Plotting Migrated Total Energy...\")\n",
                "fig_total = plot_total_energy(\n",
                "    all_stars_detectors, \n",
                "    output_filename=\"migrated_totalene_plot.pdf\"\n",
                ")"
            ]
        })

        # Max Energy
        cells_to_add.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 3. Max Flare Energy Plot (Reproducing Legacy Cell 9-11)\n",
                "print(\"Plotting Migrated Max Energy...\")\n",
                "fig_max = plot_max_energy(\n",
                "    all_stars_detectors, \n",
                "    output_filename=\"migrated_maxene_plot.pdf\",\n",
                "    show_pearson=False # Matches Cell 10\n",
                ")"
            ]
        })

        # Cumulative Energy - EK Dra
        cells_to_add.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 4. Cumulative Energy - EK Dra (Reproducing Legacy Cell 15)\n",
                "print(\"Plotting Migrated Cumulative Energy (EK Dra)...\")\n",
                "if \"EK Dra\" in all_stars_detectors:\n",
                "    fig_cum_ek = plot_cumulative_energy(\n",
                "        all_stars_detectors[\"EK Dra\"],\n",
                "        star_name=\"EK Dra\",\n",
                "        output_filename=\"migrated_cumenergy_EKDra.pdf\",\n",
                "        xticks=[0.5, 1.0, 2.0, 5.0, 10.0, 20.0, 50.0],\n",
                "        yticks=[0.05, 0.1, 0.2, 0.3, 0.5, 1]\n",
                "    )"
            ]
        })

        # Cumulative Energy - DS Tuc
        cells_to_add.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 5. Cumulative Energy - DS Tuc (Reproducing Legacy Cell 16)\n",
                "print(\"Plotting Migrated Cumulative Energy (DS Tuc)...\")\n",
                "if \"DS Tuc\" in all_stars_detectors:\n",
                "    fig_cum_ds = plot_cumulative_energy(\n",
                "        all_stars_detectors[\"DS Tuc\"],\n",
                "        star_name=\"DS Tuc\",\n",
                "        output_filename=\"migrated_cumenergy_DSTuc.pdf\",\n",
                "        xlim=(0.7, 250),\n",
                "        xticks=[1.0, 2.0, 5.0, 10.0, 20.0, 50.0, 100, 200],\n",
                "        colors=[\"#000000\", \"#E41A1C\", \"#377EB8\", \"#4DAF4A\", \"#984EA3\"]\n",
                "    )"
            ]
        })

        # Cumulative Energy - V889 Her
        cells_to_add.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 6. Cumulative Energy - V889 Her (Reproducing Legacy Cell 17)\n",
                "print(\"Plotting Migrated Cumulative Energy (V889 Her)...\")\n",
                "if \"V889 Her\" in all_stars_detectors:\n",
                "    fig_cum_v8 = plot_cumulative_energy(\n",
                "        all_stars_detectors[\"V889 Her\"],\n",
                "        star_name=\"V889 Her\",\n",
                "        output_filename=\"migrated_cumenergy_V889Her.pdf\",\n",
                "        xticks=[0.5, 1.0, 2.0, 5.0, 10.0, 20.0, 50.0, 100, 200]\n",
                "    )"
            ]
        })

        nb['cells'].extend(cells_to_add)

    # Save notebook
    with open(notebook_path, 'w') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)

    print("Notebook updated successfully!")

if __name__ == "__main__":
    main()
